name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Spécifiez une version compatible

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flask pandas matplotlib  # Ajout de Matplotlib

    - name: Check CSV File
      run: |
        if [ ! -f df_final.csv ]; then
          echo "df_final.csv not found, downloading..."
          # Ajoutez des commandes pour télécharger le fichier CSV si nécessaire
        fi

    - name: Run Tests
      run: pytest
