name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Utilisation d'une version spécifique de Python

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flask pandas
        pip install matplotlib==3.4.3  # Utilisation d'une version spécifique de Matplotlib

    - name: Debugging  # Étape de débogage
      run: |
        python --version
        pip freeze

    - name: Check CSV File
      run: |
        if [ ! -f df_final.csv ]; then
          echo "df_final.csv not found, downloading..."
          # Ajoutez des commandes pour télécharger le fichier CSV si nécessaire
        fi

    - name: Run Tests
      run: pytest
